### ISSUE TITLE
generate datasets that links Zotero records with deposits on Zenodo

### ISSUE THREAD

**Issue by jhpoelen** [bat-literature/bat-literature.github.io#48]
In attempting to query Zenodo for corresponding content known to BatLit Zotero records, 502 Bad Gateway http result codes are seen - 

```
[...]
"hash://md5/8b48687febd93560b4f06484a2c482fe","10.5281/zenodo.13[main] WARN bio.guoda.preston.store.Archiver - failed to dereference [<https://zenodo.org/api/communities/batlit/records?q=%22hash://md5/306b96829c67ef192ad6534300bab9e6%22&l=list&limit=1>]
org.apache.http.client.HttpResponseException: status code: 502, reason phrase: [<https://zenodo.org/api/communities/batlit/records?q=%22hash://md5/306b96829c67ef192ad6534300bab9e6%22&l=list&limit=1>]Bad Gateway
	at bio.guoda.preston.ResourcesHTTP.asInputStream(ResourcesHTTP.java:135)
	at bio.guoda.preston.ResourcesHTTP.asInputStream(ResourcesHTTP.java:82)
[...]

``` 

![image](https://github.com/user-attachments/assets/afe5c1f2-0534-473a-92ec-58cd1be470d7)

**Comment by jhpoelen** [comment]
Seconds later, the same query 

```
https://zenodo.org/api/communities/batlit/records?q=%22hash://md5/306b96829c67ef192ad6534300bab9e6%22&l=list&limit=1
```

yields expected results 

```
curl 'https://zenodo.org/api/communities/batlit/records?q=%22hash://md5/306b96829c67ef192ad6534300bab9e6%22&l=list&limit=1'
```
 
as 

```json 
{
  "hits": {
    "hits": [
      {
        "created": "2024-08-29T02:06:11.421175+00:00",
        "modified": "2024-08-29T02:06:11.890585+00:00",
        "id": 13421676,
        "conceptrecid": "13421675",
        "doi": "10.5281/zenodo.13421676",
        "conceptdoi": "10.5281/zenodo.13421675",
        "doi_url": "https://doi.org/10.5281/zenodo.13421676",
        "metadata": {
          "title": "On some Species of Chiroptera from Australia",
          "doi": "10.5281/zenodo.13421676",
          "publication_date": "1884",
          "description": "(Uploaded by Plazi for the Bat Literature Project) No abstract provided.",
          "access_right": "open",
          "creators": [
            {
              "name": "Leche, W.",
              "affiliation": null
            }
          ],
          "keywords": [
            "Biodiversity",
            "Mammalia",
            "Chiroptera",
            "Chordata",
            "Animalia",
            "bats",
            "bat"
          ],
          "related_identifiers": [
            {
              "identifier": "hash://md5/306b96829c67ef192ad6534300bab9e6",
              "relation": "hasVersion",
              "scheme": "url"
            },
            {
              "identifier": "hash://sha256/7ac04ba1a713fc6d05ed8abb6e82ebf2306c7ca596cec0b4ffa86bc2ee90ec73",
              "relation": "hasVersion",
              "scheme": "url"
            },
            {
              "identifier": "zotero://select/groups/5435545/items/ITUBJZWW",
              "relation": "isDerivedFrom",
              "scheme": "url"
            },
            {
              "identifier": "https://zotero.org/groups/5435545/items/ITUBJZWW",
              "relation": "isDerivedFrom",
              "scheme": "url"
            },
            {
              "identifier": "https://linker.bio/cut:hash://md5/ca66d444c83a8b95c14c82ae9883f23d!/b103008-105430",
              "relation": "isDerivedFrom",
              "scheme": "url"
            },
            {
              "identifier": "hash://md5/26f7ce5dd404e33c6570edd4ba250d20",
              "relation": "isPartOf",
              "scheme": "url"
            },
            {
              "identifier": "10.5281/zenodo.1410543",
              "relation": "isCompiledBy",
              "resource_type": "software",
              "scheme": "doi"
            }
          ],
          "custom": {
            "dwc:class": [
              "Mammalia"
            ],
            "dwc:kingdom": [
              "Animalia"
            ],
            "dwc:order": [
              "Chiroptera"
            ],
            "dwc:phylum": [
              "Chordata"
            ]
          },
          "resource_type": {
            "title": "Journal article",
            "type": "publication",
            "subtype": "article"
          },
          "journal": {
            "issue": "1",
            "pages": "49-54",
            "title": "Proceedings of the Zoological Society of London",
            "volume": "52"
          },
          "alternate_identifiers": [
            {
              "identifier": "hash://md5/306b96829c67ef192ad6534300bab9e6"
            },
            {
              "identifier": "urn:lsid:zotero.org:groups:5435545:items:ITUBJZWW"
            },
            {
              "identifier": "10.1111/j.1096-3642.1884.tb02807.x"
            }
          ],
          "license": {
            "id": "cc-by-4.0"
          },
          "communities": [
            {
              "id": "batlit"
            },
            {
              "id": "biosyslit"
            }
          ],
          "relations": {
            "version": [
              {
                "index": 0,
                "is_last": true,
                "parent": {
                  "pid_type": "recid",
                  "pid_value": "13421675"
                }
              }
            ]
          }
        },
        "title": "On some Species of Chiroptera from Australia",
        "links": {
          "self": "https://zenodo.org/api/records/13421676",
          "self_html": "https://zenodo.org/records/13421676",
          "doi": "https://doi.org/10.5281/zenodo.13421676",
          "self_doi": "https://doi.org/10.5281/zenodo.13421676",
          "self_doi_html": "https://zenodo.org/doi/10.5281/zenodo.13421676",
          "parent": "https://zenodo.org/api/records/13421675",
          "parent_html": "https://zenodo.org/records/13421675",
          "parent_doi": "https://doi.org/10.5281/zenodo.13421675",
          "parent_doi_html": "https://zenodo.org/doi/10.5281/zenodo.13421675",
          "self_iiif_manifest": "https://zenodo.org/api/iiif/record:13421676/manifest",
          "self_iiif_sequence": "https://zenodo.org/api/iiif/record:13421676/sequence/default",
          "files": "https://zenodo.org/api/records/13421676/files",
          "media_files": "https://zenodo.org/api/records/13421676/media-files",
          "thumbnails": {
            "10": "https://zenodo.org/api/iiif/record:13421676:Leche%20-%201884%20-%20On%20some%20Species%20of%20Chiroptera%20from%20Australia.pdf/full/^10,/0/default.jpg",
            "50": "https://zenodo.org/api/iiif/record:13421676:Leche%20-%201884%20-%20On%20some%20Species%20of%20Chiroptera%20from%20Australia.pdf/full/^50,/0/default.jpg",
            "100": "https://zenodo.org/api/iiif/record:13421676:Leche%20-%201884%20-%20On%20some%20Species%20of%20Chiroptera%20from%20Australia.pdf/full/^100,/0/default.jpg",
            "250": "https://zenodo.org/api/iiif/record:13421676:Leche%20-%201884%20-%20On%20some%20Species%20of%20Chiroptera%20from%20Australia.pdf/full/^250,/0/default.jpg",
            "750": "https://zenodo.org/api/iiif/record:13421676:Leche%20-%201884%20-%20On%20some%20Species%20of%20Chiroptera%20from%20Australia.pdf/full/^750,/0/default.jpg",
            "1200": "https://zenodo.org/api/iiif/record:13421676:Leche%20-%201884%20-%20On%20some%20Species%20of%20Chiroptera%20from%20Australia.pdf/full/^1200,/0/default.jpg"
          },
          "archive": "https://zenodo.org/api/records/13421676/files-archive",
          "archive_media": "https://zenodo.org/api/records/13421676/media-files-archive",
          "latest": "https://zenodo.org/api/records/13421676/versions/latest",
          "latest_html": "https://zenodo.org/records/13421676/latest",
          "versions": "https://zenodo.org/api/records/13421676/versions",
          "draft": "https://zenodo.org/api/records/13421676/draft",
          "reserve_doi": "https://zenodo.org/api/records/13421676/draft/pids/doi",
          "access_links": "https://zenodo.org/api/records/13421676/access/links",
          "access_grants": "https://zenodo.org/api/records/13421676/access/grants",
          "access_users": "https://zenodo.org/api/records/13421676/access/users",
          "access_request": "https://zenodo.org/api/records/13421676/access/request",
          "access": "https://zenodo.org/api/records/13421676/access",
          "communities": "https://zenodo.org/api/records/13421676/communities",
          "communities-suggestions": "https://zenodo.org/api/records/13421676/communities-suggestions",
          "requests": "https://zenodo.org/api/records/13421676/requests"
        },
        "updated": "2024-08-29T02:06:11.890585+00:00",
        "recid": "13421676",
        "revision": 5,
        "files": [
          {
            "id": "8ba86d91-cdb2-4d7c-a77f-bc131d36c4c0",
            "key": "Leche - 1884 - On some Species of Chiroptera from Australia.pdf",
            "size": 1402232,
            "checksum": "md5:306b96829c67ef192ad6534300bab9e6",
            "links": {
              "self": "https://zenodo.org/api/records/13421676/files/Leche - 1884 - On some Species of Chiroptera from Australia.pdf/content"
            }
          }
        ],
        "swh": {},
        "owners": [
          {
            "id": "7292"
          }
        ],
        "status": "published",
        "stats": {
          "downloads": 2,
          "unique_downloads": 2,
          "views": 6,
          "unique_views": 6,
          "version_downloads": 2,
          "version_unique_downloads": 2,
          "version_unique_views": 6,
          "version_views": 6
        },
        "state": "done",
        "submitted": true
      }
    ],
    "total": 1
  },
  "aggregations": {
    "access_status": {
      "buckets": [
        {
          "key": "open",
          "doc_count": 1,
          "label": "Open",
          "is_selected": false
        }
      ],
      "label": "Access status"
    },
    "resource_type": {
      "buckets": [
        {
          "key": "publication",
          "doc_count": 1,
          "label": "Publication",
          "is_selected": false,
          "inner": {
            "buckets": [
              {
                "key": "publication-article",
                "doc_count": 1,
                "label": "Journal article",
                "is_selected": false
              }
            ]
          }
        }
      ],
      "label": "Resource types"
    },
    "subject": {
      "buckets": [
        {
          "key": "Animalia",
          "doc_count": 1,
          "label": "Animalia",
          "is_selected": false
        },
        {
          "key": "Biodiversity",
          "doc_count": 1,
          "label": "Biodiversity",
          "is_selected": false
        },
        {
          "key": "Chiroptera",
          "doc_count": 1,
          "label": "Chiroptera",
          "is_selected": false
        },
        {
          "key": "Chordata",
          "doc_count": 1,
          "label": "Chordata",
          "is_selected": false
        },
        {
          "key": "Mammalia",
          "doc_count": 1,
          "label": "Mammalia",
          "is_selected": false
        },
        {
          "key": "bat",
          "doc_count": 1,
          "label": "bat",
          "is_selected": false
        },
        {
          "key": "bats",
          "doc_count": 1,
          "label": "bats",
          "is_selected": false
        }
      ],
      "label": "Subjects"
    },
    "file_type": {
      "buckets": [
        {
          "key": "pdf",
          "doc_count": 1,
          "label": "PDF",
          "is_selected": false
        }
      ],
      "label": "File type"
    }
  },
  "links": {
    "self": "https://zenodo.org/api/communities/batlit/records?page=1&q=%22hash%3A%2F%2Fmd5%2F306b96829c67ef192ad6534300bab9e6%22&size=25&sort=bestmatch"
  }
}
```

**Comment by jhpoelen** [comment]
A dataset linking versioned Zotero records with associated records on Zenodo can be found at https://batlit.org/zenodo/refs-on-zenodo.csv  and https://batlit.org/zenodo/refs-on-zenodo-100.csv .

fyi @myrmoteras

**Comment by jhpoelen** [comment]
@myrmoteras thanks for responding

Here's what I had to do to make a versioned snapshot of Zenodo metadata associated with BatLit content:

1. write a script to mine Zenodo metadata associated with content from a specific BatLit version (minutes, [track-zenodo-association.sh](https://github.com/bat-literature/bat-literature.github.io/blob/0e7f5b5dd70bf70087bf3103a10f7489bea781ad/bin/track-zenodo-associations.sh))
2. track and store Zenodo metadata associated with BatLit content (212 minutes ~ 3-4 hours, ~300 MB of metadata resulting from tens of thousands of web api requests, with a few [http error messages](https://github.com/bat-literature/bat-literature.github.io/issues/48) causing potential unrecoverable dataloss, see https://github.com/bat-literature/bat-literature.github.io/blob/0e7f5b5dd70bf70087bf3103a10f7489bea781ad/zenodo)
3. write a scripts to associate zenodo DOIs with BatLit content (hours, [hash2zenodo.sh](https://github.com/bat-literature/bat-literature.github.io/blob/0e7f5b5dd70bf70087bf3103a10f7489bea781ad/bin/hash2zenodo.sh), [refs2zenodo.sh](https://github.com/bat-literature/bat-literature.github.io/blob/0e7f5b5dd70bf70087bf3103a10f7489bea781ad/bin/refs2zenodo.sh))
4. publish [refs-on-zenodo.csv](https://github.com/bat-literature/bat-literature.github.io/blob/0e7f5b5dd70bf70087bf3103a10f7489bea781ad/zenodo/refs-on-zenodo.csv) and [refs-on-zenodo-100.csv](https://github.com/bat-literature/bat-literature.github.io/blob/0e7f5b5dd70bf70087bf3103a10f7489bea781ad/zenodo/refs-on-zenodo-100.csv) (minutes)

sample record, generated from 

```
cat zenodo/refs-on-zenodo-100.csv | head -2 | mlr --icsv --oxtab cat
```

and based on BatLit v0.7 hash://md5/ce1e7618f237ff56e74d51f496e811a3 (aka corpusId) and Zenodo's BatLit Metadata v0.1 hash://md5/fe634ab84d48b6a9b58adc9e038ecd86 (aka zenodoResponseCorpusId):


```
authors                Douglas
date                   1967
title                  Article: The Natural History of the Ghost Bat, Macroderma Gigas (Microchiroptera Megadermatidae), in Western Australia
journal                Western Australia. The Western Australian Naturalist
doi                    
id                     https://www.zotero.org/groups/bat_literature_project/items/M5MZ6NSB
attachment             https://api.zotero.org/groups/5435545/items/223GU789
attachmentId           hash://md5/5e3f7fac483550be7983c6096e9e9800
corpusId               hash://md5/ce1e7618f237ff56e74d51f496e811a3
alternativeDoi         10.5281/zenodo.13521017
alternativeDoiUrl      https://doi.org/10.5281/zenodo.13521017
zenodoResponseCorpusId hash://md5/fe634ab84d48b6a9b58adc9e038ecd86
```


And, this list (i.e., refs-on-zenodo.csv) is outdated as soon as it is published . . . because . . . metadata for Zenodo deposits has/can/will change in format, content as there's no way for me to algorithmically verify the authenticity content and metadata associated with some Zenodo DOI or deposit id. 

In other words, with the current tools and APIs provided by Zenodo, I cannot validate the integrity of the associations of the versioned batlit corpus and their associated Zenodo records (metadata and files) using the corpora I have on file. Instead, I have to constantly poll Zenodo and someone compare the provided metadata and content with the published BatLit corpus.

When building BatLit (and other digital datasets), there's some guiding questions I use to guide tool and infrastructure development:

1. How to keep track of BatLit data corpus?
2. How to cite specific versions of the BatLit data corpora?
3. How to share specific versions of the BatLit data corpora?

Now, I am curious how these questions can be answered using the Zenodo's user friendly communities functionality to compile, manage, and export/share versioned corpora. With the tools / infrastructure, I am aware of, I'd have to revert to web scraping to effectively rebuild batlit from Zenodo instead of Zotero, which seems like double work.

I wonder what the Zenodo technical team (ping @slint) will come up with to satisfy your use case and how your proposed Zenodo -> BiodiversityPMC workflow will be implemented. 

Thanks for being patient in discussing these pesky data publication challenges.

_Originally posted by @jhpoelen in https://github.com/plazi/Biodiversity-Literature-Repository/issues/106#issuecomment-2540272086_

**Comment by jhpoelen** [comment]
PS, just in case you are interested in the responses from Zenodo, you can see all of them by pasting this into your bash terminal after installing [preston](https://github.com/bio-guoda/preston).


```bash
preston ls\
 --anchor hash://md5/fe634ab84d48b6a9b58adc9e038ecd86\
 --remote https://raw.githubusercontent.com/bat-literature/bat-literature.github.io/0e7f5b5dd70bf70087bf3103a10f7489bea781ad/zenodo\
 | preston cat\
 --remote https://raw.githubusercontent.com/bat-literature/bat-literature.github.io/0e7f5b5dd70bf70087bf3103a10f7489bea781ad/zenodo
```

Alternatively, you can download the data yourself using https://github.com/bat-literature/bat-literature.github.io/archive/0e7f5b5dd70bf70087bf3103a10f7489bea781ad.zip and peek in the '/zenodo' folder.

_Originally posted by @jhpoelen in https://github.com/plazi/Biodiversity-Literature-Repository/issues/106#issuecomment-2540289974_

**Comment by jhpoelen** [comment]
If you just want to see a single record, you can select the first record from the corpus,

```bash
preston ls\
 --anchor hash://md5/fe634ab84d48b6a9b58adc9e038ecd86\
 --remote https://raw.githubusercontent.com/bat-literature/bat-literature.github.io/0e7f5b5dd70bf70087bf3103a10f7489bea781ad/zenodo\
 | grep hasVersion\
 | head -1\
 | preston cat\
 --remote https://raw.githubusercontent.com/bat-literature/bat-literature.github.io/0e7f5b5dd70bf70087bf3103a10f7489bea781ad/zenodo 
```

to get the content associated with the query response 

```
<https://zenodo.org/api/communities/batlit/records?q=%22hash://md5/5e3f7fac483550be7983c6096e9e9800%22&l=list&limit=1> <http://purl.org/pav/hasVersion> <hash://md5/6d291be2f337911396f5f62d2fc165f8> <urn:uuid:520682a0-244b-4da7-883a-f6cc4964ccc3> .
```

which, at time of writing, can also be found at 

https://github.com/bat-literature/bat-literature.github.io/blob/main/zenodo/6d/29/6d291be2f337911396f5f62d2fc165f8

with a "raw" data stream available via  

https://raw.githubusercontent.com/bat-literature/bat-literature.github.io/refs/heads/main/zenodo/6d/29/6d291be2f337911396f5f62d2fc165f8

_Originally posted by @jhpoelen in https://github.com/plazi/Biodiversity-Literature-Repository/issues/106#issuecomment-2540295403_
